coalesce(tdaf.app_id, tdti.app_id, tdta.app_id, tdba.app_id, tdbi.app_id) as app_id,
coalesce(tdaf.Project, tdti.Project, tdta.Project, tdba.Project, tdbi.Project) as Project,
coalesce(tdaf.Version, tdti.Version, tdta.Version, tdba.Version, tdbi.Version) as Version,
coalesce(tdaf.platform, tdti.platform, tdta.platform, tdba.platform, tdbi.platform) as platform,
coalesce(tdaf.event_date, tdti.event_date, tdta.event_date, tdba.event_date, tdbi.event_date) as event_date,
coalesce(tdaf.country_code, tdti.country_code, tdta.country_code, tdba.country_code, tdbi.country_code) as country_code,
coalesce(tdaf.country, tdti.country, tdta.country, tdba.country, tdbi.country) as country,
coalesce(tdaf.media_source, tdti.media_source, tdta.media_source, tdba.media_source, tdbi.media_source) as media_source,
coalesce(tdaf.campaign, tdti.campaign, tdta.campaign, tdba.campaign, tdbi.campaign) as campaign,
coalesce(clicks, 0) as clicks,
coalesce(installs, 0) as installs,
coalesce(total_cost, 0) as total_cost,
coalesce(iap_rev, 0) as iap_rev,
coalesce(ads_rev, 0) as ads_rev,
coalesce(iap_brev, 0) as iap_brev,
coalesce(ads_brev, 0) as ads_brev

coalesce(slaf.app_id, slti.app_id, slta.app_id, slba.app_id, slbi.app_id) as app_id,
        coalesce(slaf.Project, slti.Project, slta.Project, slba.Project, slbi.Project) as Project,
        coalesce(slaf.Version, slti.Version, slta.Version, slba.Version, slbi.Version) as Version,
        coalesce(slaf.platform, slti.platform, slta.platform, slba.platform, slbi.platform) as platform,
        coalesce(slaf.event_date, slti.event_date, slta.event_date, slba.event_date, slbi.event_date) as event_date,
        coalesce(slaf.country_code, slti.country_code, slta.country_code, slba.country_code, slbi.country_code) as country_code,
        coalesce(slaf.country, slti.country, slta.country, slba.country, slbi.country) as country,
        coalesce(slaf.media_source, slti.media_source, slta.media_source, slba.media_source, slbi.media_source) as media_source,
        coalesce(slaf.campaign, slti.campaign, slta.campaign, slba.campaign, slbi.campaign) as campaign,
        coalesce(clicks, 0) as clicks,
        coalesce(installs, 0) as installs,
        coalesce(total_cost, 0) as total_cost,
        coalesce(iap_rev, 0) as iap_rev,
        coalesce(ads_rev, 0) as ads_rev,
        coalesce(iap_brev, 0) as iap_brev,
        coalesce(ads_brev, 0) as ads_brev

        coalesce(seaf.app_id, seti.app_id, seta.app_id, seba.app_id, sebi.app_id) as app_id,
                coalesce(seaf.Project, seti.Project, seta.Project, seba.Project, sebi.Project) as Project,
                coalesce(seaf.Version, seti.Version, seta.Version, seba.Version, sebi.Version) as Version,
                coalesce(seaf.platform, seti.platform, seta.platform, seba.platform, sebi.platform) as platform,
                coalesce(seaf.event_date, seti.event_date, seta.event_date, seba.event_date, sebi.event_date) as event_date,
                coalesce(seaf.country_code, seti.country_code, seta.country_code, seba.country_code, sebi.country_code) as country_code,
                coalesce(seaf.country, seti.country, seta.country, seba.country, sebi.country) as country,
                coalesce(seaf.media_source, seti.media_source, seta.media_source, seba.media_source, sebi.media_source) as media_source,
                coalesce(seaf.campaign, seti.campaign, seta.campaign, seba.campaign, sebi.campaign) as campaign,
                coalesce(impressions, 0) as impressions,
                coalesce(clicks, 0) as clicks,
                coalesce(installs, 0) as installs,
                coalesce(total_cost, 0) as total_cost,
                coalesce(iap_rev, 0) as iap_rev,
                coalesce(ads_rev, 0) as ads_rev,
                coalesce(iap_brev, 0) as iap_brev,
                coalesce(ads_brev, 0) as ads_brev
